// src/components/Toolbar.tsx
import { memo, useState } from 'react';
import { TOOLBAR, SPACING, ANIMATION, COLORS } from '../utils/constants';

interface ToolbarProps {
  onAutoArrange: () => void;
  onZoomIn: () => void;
  onZoomOut: () => void;
  onZoomReset: () => void;
  onFitToScreen: () => void;
  onExportPNG: () => void;
  onClearCanvas: () => void;
  zoomPercentage: number;
}

interface ToolbarButtonProps {
  icon: string;
  label: string;
  onClick: () => void;
  disabled?: boolean;
}

const ToolbarButton = memo(({ icon, label, onClick, disabled }: ToolbarButtonProps) => {
  const [isHovered, setIsHovered] = useState(false);
  const [isActive, setIsActive] = useState(false);

  return (
    <button
      style={{
        width: `${TOOLBAR.buttonSize}px`,
        height: `${TOOLBAR.buttonSize}px`,
        borderRadius: `${TOOLBAR.buttonRadius}px`,
        backgroundColor: isActive
          ? TOOLBAR.activeBg
          : isHovered
          ? TOOLBAR.hoverBg
          : 'transparent',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: `${TOOLBAR.iconSize}px`,
        color: disabled ? COLORS.textSecondary : '#495057',
        cursor: disabled ? 'not-allowed' : 'pointer',
        opacity: disabled ? 0.4 : 1,
        transition: `background-color ${ANIMATION.fast}ms ${ANIMATION.easing}`,
        border: 'none',
        outline: 'none',
      }}
      onClick={onClick}
      onMouseEnter={() => !disabled && setIsHovered(true)}
      onMouseLeave={() => {
        setIsHovered(false);
        setIsActive(false);
      }}
      onMouseDown={() => !disabled && setIsActive(true)}
      onMouseUp={() => setIsActive(false)}
      title={label}
      disabled={disabled}
    >
      {icon}
    </button>
  );
});

ToolbarButton.displayName = 'ToolbarButton';

const Separator = () => (
  <div
    style={{
      width: '1px',
      height: `${TOOLBAR.buttonSize * 0.6}px`,
      backgroundColor: '#DEE2E6',
    }}
  />
);

export const Toolbar = memo(
  ({
    onAutoArrange,
    onZoomIn,
    onZoomOut,
    onZoomReset,
    onFitToScreen,
    onExportPNG,
    onClearCanvas,
    zoomPercentage,
  }: ToolbarProps) => {
    return (
      <div
        style={{
          position: 'fixed',
          top: '20px',
          left: '50%',
          transform: 'translateX(-50%)',
          display: 'flex',
          alignItems: 'center',
          gap: `${SPACING.sm}px`,
          padding: TOOLBAR.padding,
          backgroundColor: TOOLBAR.bg,
          borderRadius: `${TOOLBAR.borderRadius}px`,
          boxShadow: TOOLBAR.shadow,
          backdropFilter: `blur(${TOOLBAR.backdropBlur}px)`,
          zIndex: 1000,
          userSelect: 'none',
        }}
      >
        <ToolbarButton icon="⚡" label="Auto Arrange" onClick={onAutoArrange} />

        <Separator />

        <ToolbarButton icon="−" label="Zoom out (Ctrl+-)" onClick={onZoomOut} />
        <button
          style={{
            minWidth: `${TOOLBAR.buttonSize * 1.5}px`,
            height: `${TOOLBAR.buttonSize}px`,
            borderRadius: `${TOOLBAR.buttonRadius}px`,
            backgroundColor: 'transparent',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: '11px',
            fontWeight: 600,
            color: '#495057',
            cursor: 'pointer',
            border: 'none',
            outline: 'none',
          }}
          onClick={onZoomReset}
          title="Reset zoom (Ctrl+0)"
        >
          {zoomPercentage}%
        </button>
        <ToolbarButton icon="+" label="Zoom in (Ctrl++)" onClick={onZoomIn} />

        <Separator />

        <ToolbarButton icon="⛶" label="Fit all nodes" onClick={onFitToScreen} />
        <ToolbarButton icon="📥" label="Download as image" onClick={onExportPNG} />
        <ToolbarButton icon="🗑" label="Delete all nodes" onClick={onClearCanvas} />
      </div>
    );
  }
);

Toolbar.displayName = 'Toolbar';

// src/components/Toolbar.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  function handleZoomIn() {
    dispatch('zoom-in');
  }

  function handleZoomOut() {
    dispatch('zoom-out');
  }

  function handleZoomReset() {
    dispatch('zoom-reset');
  }

  function handleFitToScreen() {
    dispatch('fit-to-screen');
  }

  function handleClearCanvas() {
    if (confirm('Are you sure you want to clear all nodes?')) {
      dispatch('clear-canvas');
    }
  }
</script>

<div class="toolbar">
  <button class="toolbar-btn" on:click={handleZoomOut} title="Zoom out (Ctrl+-)">
    <span class="icon">−</span>
  </button>

  <button class="toolbar-btn" on:click={handleZoomReset} title="Reset zoom (Ctrl+0)">
    <span class="text">100%</span>
  </button>

  <button class="toolbar-btn" on:click={handleZoomIn} title="Zoom in (Ctrl++)">
    <span class="icon">+</span>
  </button>

  <div class="separator"></div>

  <button class="toolbar-btn" on:click={handleFitToScreen} title="Fit all nodes">
    <span class="icon">⛶</span>
  </button>

  <div class="separator"></div>

  <button class="toolbar-btn danger" on:click={handleClearCanvas} title="Clear canvas">
    <span class="icon">🗑</span>
  </button>
</div>

<style>
  .toolbar {
    position: fixed;
    top: 20px;
    left: 50%;
    transform: translateX(-50%);
    z-index: 1000;

    display: flex;
    align-items: center;
    gap: 4px;

    background: rgba(255, 255, 255, 0.9);
    backdrop-filter: blur(8px);
    border-radius: 12px;
    padding: 8px 12px;
    box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.1);
  }

  .toolbar-btn {
    width: 36px;
    height: 36px;
    border: none;
    background: transparent;
    border-radius: 6px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: background 150ms ease;
    color: #495057;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  }

  .toolbar-btn:hover {
    background: #F1F3F5;
  }

  .toolbar-btn:active {
    background: #E9ECEF;
  }

  .toolbar-btn.danger:hover {
    background: #FFE5E5;
    color: #C92A2A;
  }

  .icon {
    font-size: 18px;
    line-height: 1;
  }

  .text {
    font-size: 12px;
    font-weight: 600;
  }

  .separator {
    width: 1px;
    height: 24px;
    background: #DEE2E6;
    margin: 0 4px;
  }
</style>
